version: '3.8'

services:
  cc-api:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: [ '/usr/src/app/entrypoint.sh' ]
    volumes:
      - '.:/usr/src/app'
    ports:
    # Make sure 5004 port is available
      - 5004:5000
    environment:
      - FLASK_APP=manage.py
      - FLASK_DEBUG=1
      - FLASK_ENV=development
      - APP_SETTINGS=src.config.DevelopmentConfig
      - DATABASE_URL=postgresql://postgres:postgres@api-dev-db:5432/api_dev
      - DATABASE_TEST_URL=postgresql://postgres:postgres@api-test-db:5432/api_test
      # Example of how to make an environmental variable:
      # - OPENAI_API_KEY=${OPENAI_API_KEY} 

    depends_on:
      - cc-api-dev-db
      - cc-api-test-db

  cc-api-dev-db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - 5432 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  cc-api-test-db:
    build:
      context: ./src/db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
